### ISSUE TITLE
Built-in languages

### ISSUE THREAD

**Issue by curlpipe** [curlpipe/synoptic#1]
Include pre-defined highlighters. 
  - [X] Rust
  - [X] Python
  - [x] Java
  - [x] Javascript
  - [x] C#
  - [x] PHP
  - [x] C
  - [x] C++
  - [x] R
  - [ ] Objective-C
  - [x] Swift
  - [x] TypeScript
  - [x] CSS
  - [x] HTML
  - [x] MD
  - [x] SQL
  - [x] MATLAB
  - [x] Perl
  - [x] Assembly
  - [x] Go
  - [x] Ruby

**Comment by rauschma** [comment]
JavaScript will be an interesting challenge because you can nest expressions inside template literals (a kind of string literal) – e.g.:

```js
`template literal ${`nested` + `expression`}`
```

**Comment by curlpipe** [comment]
Implemented all of the above languages (except Objective-C due to a conflict in file extensions)
